version: '3'
services:
  api:
    image: golang:1.15
    entrypoint: go run main.go
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_SSLMODE=disable
    links:
      - db
  db:
    image: postgres:12.4
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
